"""Initial production schema

Revision ID: 635eb29d24e5
Revises: 
Create Date: 2026-04-13 06:32:31.096144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '635eb29d24e5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_aggregates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('positive_count', sa.Integer(), nullable=True),
    sa.Column('negative_count', sa.Integer(), nullable=True),
    sa.Column('neutral_count', sa.Integer(), nullable=True),
    sa.Column('avg_polarity', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'platform', name='uix_date_platform')
    )
    op.create_index(op.f('ix_daily_aggregates_date'), 'daily_aggregates', ['date'], unique=False)
    op.create_index(op.f('ix_daily_aggregates_id'), 'daily_aggregates', ['id'], unique=False)
    op.create_index(op.f('ix_daily_aggregates_platform'), 'daily_aggregates', ['platform'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('avg_sentiment', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_id'), 'topics', ['id'], unique=False)
    op.create_index(op.f('ix_topics_name'), 'topics', ['name'], unique=False)
    op.create_table('tweets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tweets_created_at'), 'tweets', ['created_at'], unique=False)
    op.create_index(op.f('ix_tweets_id'), 'tweets', ['id'], unique=False)
    op.create_index(op.f('ix_tweets_platform'), 'tweets', ['platform'], unique=False)
    op.create_index(op.f('ix_tweets_platform_id'), 'tweets', ['platform_id'], unique=True)
    op.create_table('sentiment_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tweet_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('polarity', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tweet_id')
    )
    op.create_index(op.f('ix_sentiment_results_id'), 'sentiment_results', ['id'], unique=False)
    op.create_index(op.f('ix_sentiment_results_label'), 'sentiment_results', ['label'], unique=False)
    op.create_table('topic_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tweet_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_associations_id'), 'topic_associations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_associations_id'), table_name='topic_associations')
    op.drop_table('topic_associations')
    op.drop_index(op.f('ix_sentiment_results_label'), table_name='sentiment_results')
    op.drop_index(op.f('ix_sentiment_results_id'), table_name='sentiment_results')
    op.drop_table('sentiment_results')
    op.drop_index(op.f('ix_tweets_platform_id'), table_name='tweets')
    op.drop_index(op.f('ix_tweets_platform'), table_name='tweets')
    op.drop_index(op.f('ix_tweets_id'), table_name='tweets')
    op.drop_index(op.f('ix_tweets_created_at'), table_name='tweets')
    op.drop_table('tweets')
    op.drop_index(op.f('ix_topics_name'), table_name='topics')
    op.drop_index(op.f('ix_topics_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_daily_aggregates_platform'), table_name='daily_aggregates')
    op.drop_index(op.f('ix_daily_aggregates_id'), table_name='daily_aggregates')
    op.drop_index(op.f('ix_daily_aggregates_date'), table_name='daily_aggregates')
    op.drop_table('daily_aggregates')
    # ### end Alembic commands ###
